//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/InputActions/Player_InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions/Player_InputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Player_InputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Player_InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Player_InputActions"",
    ""maps"": [
        {
            ""name"": ""WhackAMole"",
            ""id"": ""2959179e-4767-443d-9c01-363bfa296c7a"",
            ""actions"": [
                {
                    ""name"": ""Select1"",
                    ""type"": ""Button"",
                    ""id"": ""49c42b32-8d38-4008-a92b-0c95f587f781"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select2"",
                    ""type"": ""Button"",
                    ""id"": ""0c1cc8b4-491e-4a1d-b225-2f1a93c79606"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select3"",
                    ""type"": ""Button"",
                    ""id"": ""8a054ede-20d5-4e05-999e-ba237c346bfe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select4"",
                    ""type"": ""Button"",
                    ""id"": ""a480e23f-0e2b-4f74-94ce-a17ac49a3a6b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1b9cfff9-8bad-4594-9f79-7cc91293fe18"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b37bb81-903a-4fe2-bcec-b60019666d45"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f1efb8-9d7e-482f-9469-3ff4f08a0b3a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aff4f88-8284-4d77-aa10-3488c0dfbda2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Baseball"",
            ""id"": ""d35911f2-eaaa-4154-b8f8-db3e08c52d49"",
            ""actions"": [
                {
                    ""name"": ""Hit"",
                    ""type"": ""Button"",
                    ""id"": ""35b2d511-44da-4199-a93d-cd55efdde7c1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa079ce0-3e8d-4a37-95f4-e897d71fc01d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a9e8bb8-fa83-429f-9f1a-5e631f4607d0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ColorBlock"",
            ""id"": ""eba7a927-4419-485c-9f9f-4e59d8e892b1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""441a7a5a-13c1-4ff8-a24e-3661d12b7b8a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1cac137b-b268-4410-95bb-ae224692ca3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0cf5698f-07b3-4ab5-bfe1-5f39c3e28d48"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b35c8a36-5ed9-4f8e-95de-6ca45b67b0f9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7031ad1c-e510-4d91-a36c-c02e3fa9cf27"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f9fd0f27-472d-49e1-8398-40916d4e8b1e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""96453df4-ea21-4c11-a2e6-d3d03c2e6385"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c59d93f1-3d3e-42a1-814f-d92422349df7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""31c978fb-c3d5-4d10-9a84-2441511de549"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cd4edc22-8fe2-461b-b92b-be2ba297e87a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7d3871d6-da51-4789-bdb2-e01c34974c8c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""69535a5a-8059-4bef-b803-8adf49c3b230"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e5e28ca-7511-4587-a4f3-5ee33433f208"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // WhackAMole
        m_WhackAMole = asset.FindActionMap("WhackAMole", throwIfNotFound: true);
        m_WhackAMole_Select1 = m_WhackAMole.FindAction("Select1", throwIfNotFound: true);
        m_WhackAMole_Select2 = m_WhackAMole.FindAction("Select2", throwIfNotFound: true);
        m_WhackAMole_Select3 = m_WhackAMole.FindAction("Select3", throwIfNotFound: true);
        m_WhackAMole_Select4 = m_WhackAMole.FindAction("Select4", throwIfNotFound: true);
        // Baseball
        m_Baseball = asset.FindActionMap("Baseball", throwIfNotFound: true);
        m_Baseball_Hit = m_Baseball.FindAction("Hit", throwIfNotFound: true);
        // ColorBlock
        m_ColorBlock = asset.FindActionMap("ColorBlock", throwIfNotFound: true);
        m_ColorBlock_Move = m_ColorBlock.FindAction("Move", throwIfNotFound: true);
        m_ColorBlock_Jump = m_ColorBlock.FindAction("Jump", throwIfNotFound: true);
    }

    ~@Player_InputActions()
    {
        UnityEngine.Debug.Assert(!m_WhackAMole.enabled, "This will cause a leak and performance issues, Player_InputActions.WhackAMole.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Baseball.enabled, "This will cause a leak and performance issues, Player_InputActions.Baseball.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ColorBlock.enabled, "This will cause a leak and performance issues, Player_InputActions.ColorBlock.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // WhackAMole
    private readonly InputActionMap m_WhackAMole;
    private List<IWhackAMoleActions> m_WhackAMoleActionsCallbackInterfaces = new List<IWhackAMoleActions>();
    private readonly InputAction m_WhackAMole_Select1;
    private readonly InputAction m_WhackAMole_Select2;
    private readonly InputAction m_WhackAMole_Select3;
    private readonly InputAction m_WhackAMole_Select4;
    /// <summary>
    /// Provides access to input actions defined in input action map "WhackAMole".
    /// </summary>
    public struct WhackAMoleActions
    {
        private @Player_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public WhackAMoleActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/Select1".
        /// </summary>
        public InputAction @Select1 => m_Wrapper.m_WhackAMole_Select1;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/Select2".
        /// </summary>
        public InputAction @Select2 => m_Wrapper.m_WhackAMole_Select2;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/Select3".
        /// </summary>
        public InputAction @Select3 => m_Wrapper.m_WhackAMole_Select3;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/Select4".
        /// </summary>
        public InputAction @Select4 => m_Wrapper.m_WhackAMole_Select4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_WhackAMole; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="WhackAMoleActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(WhackAMoleActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions" />
        public void AddCallbacks(IWhackAMoleActions instance)
        {
            if (instance == null || m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Add(instance);
            @Select1.started += instance.OnSelect1;
            @Select1.performed += instance.OnSelect1;
            @Select1.canceled += instance.OnSelect1;
            @Select2.started += instance.OnSelect2;
            @Select2.performed += instance.OnSelect2;
            @Select2.canceled += instance.OnSelect2;
            @Select3.started += instance.OnSelect3;
            @Select3.performed += instance.OnSelect3;
            @Select3.canceled += instance.OnSelect3;
            @Select4.started += instance.OnSelect4;
            @Select4.performed += instance.OnSelect4;
            @Select4.canceled += instance.OnSelect4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions" />
        private void UnregisterCallbacks(IWhackAMoleActions instance)
        {
            @Select1.started -= instance.OnSelect1;
            @Select1.performed -= instance.OnSelect1;
            @Select1.canceled -= instance.OnSelect1;
            @Select2.started -= instance.OnSelect2;
            @Select2.performed -= instance.OnSelect2;
            @Select2.canceled -= instance.OnSelect2;
            @Select3.started -= instance.OnSelect3;
            @Select3.performed -= instance.OnSelect3;
            @Select3.canceled -= instance.OnSelect3;
            @Select4.started -= instance.OnSelect4;
            @Select4.performed -= instance.OnSelect4;
            @Select4.canceled -= instance.OnSelect4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />.
        /// </summary>
        /// <seealso cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />
        public void RemoveCallbacks(IWhackAMoleActions instance)
        {
            if (m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions.AddCallbacks(IWhackAMoleActions)" />
        /// <seealso cref="WhackAMoleActions.RemoveCallbacks(IWhackAMoleActions)" />
        /// <seealso cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />
        public void SetCallbacks(IWhackAMoleActions instance)
        {
            foreach (var item in m_Wrapper.m_WhackAMoleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="WhackAMoleActions" /> instance referencing this action map.
    /// </summary>
    public WhackAMoleActions @WhackAMole => new WhackAMoleActions(this);

    // Baseball
    private readonly InputActionMap m_Baseball;
    private List<IBaseballActions> m_BaseballActionsCallbackInterfaces = new List<IBaseballActions>();
    private readonly InputAction m_Baseball_Hit;
    /// <summary>
    /// Provides access to input actions defined in input action map "Baseball".
    /// </summary>
    public struct BaseballActions
    {
        private @Player_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BaseballActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Baseball/Hit".
        /// </summary>
        public InputAction @Hit => m_Wrapper.m_Baseball_Hit;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Baseball; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BaseballActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BaseballActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BaseballActions" />
        public void AddCallbacks(IBaseballActions instance)
        {
            if (instance == null || m_Wrapper.m_BaseballActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BaseballActionsCallbackInterfaces.Add(instance);
            @Hit.started += instance.OnHit;
            @Hit.performed += instance.OnHit;
            @Hit.canceled += instance.OnHit;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BaseballActions" />
        private void UnregisterCallbacks(IBaseballActions instance)
        {
            @Hit.started -= instance.OnHit;
            @Hit.performed -= instance.OnHit;
            @Hit.canceled -= instance.OnHit;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BaseballActions.UnregisterCallbacks(IBaseballActions)" />.
        /// </summary>
        /// <seealso cref="BaseballActions.UnregisterCallbacks(IBaseballActions)" />
        public void RemoveCallbacks(IBaseballActions instance)
        {
            if (m_Wrapper.m_BaseballActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BaseballActions.AddCallbacks(IBaseballActions)" />
        /// <seealso cref="BaseballActions.RemoveCallbacks(IBaseballActions)" />
        /// <seealso cref="BaseballActions.UnregisterCallbacks(IBaseballActions)" />
        public void SetCallbacks(IBaseballActions instance)
        {
            foreach (var item in m_Wrapper.m_BaseballActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BaseballActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BaseballActions" /> instance referencing this action map.
    /// </summary>
    public BaseballActions @Baseball => new BaseballActions(this);

    // ColorBlock
    private readonly InputActionMap m_ColorBlock;
    private List<IColorBlockActions> m_ColorBlockActionsCallbackInterfaces = new List<IColorBlockActions>();
    private readonly InputAction m_ColorBlock_Move;
    private readonly InputAction m_ColorBlock_Jump;
    /// <summary>
    /// Provides access to input actions defined in input action map "ColorBlock".
    /// </summary>
    public struct ColorBlockActions
    {
        private @Player_InputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ColorBlockActions(@Player_InputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ColorBlock/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_ColorBlock_Move;
        /// <summary>
        /// Provides access to the underlying input action "ColorBlock/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_ColorBlock_Jump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ColorBlock; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ColorBlockActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ColorBlockActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ColorBlockActions" />
        public void AddCallbacks(IColorBlockActions instance)
        {
            if (instance == null || m_Wrapper.m_ColorBlockActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ColorBlockActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ColorBlockActions" />
        private void UnregisterCallbacks(IColorBlockActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ColorBlockActions.UnregisterCallbacks(IColorBlockActions)" />.
        /// </summary>
        /// <seealso cref="ColorBlockActions.UnregisterCallbacks(IColorBlockActions)" />
        public void RemoveCallbacks(IColorBlockActions instance)
        {
            if (m_Wrapper.m_ColorBlockActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ColorBlockActions.AddCallbacks(IColorBlockActions)" />
        /// <seealso cref="ColorBlockActions.RemoveCallbacks(IColorBlockActions)" />
        /// <seealso cref="ColorBlockActions.UnregisterCallbacks(IColorBlockActions)" />
        public void SetCallbacks(IColorBlockActions instance)
        {
            foreach (var item in m_Wrapper.m_ColorBlockActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ColorBlockActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ColorBlockActions" /> instance referencing this action map.
    /// </summary>
    public ColorBlockActions @ColorBlock => new ColorBlockActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "WhackAMole" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="WhackAMoleActions.AddCallbacks(IWhackAMoleActions)" />
    /// <seealso cref="WhackAMoleActions.RemoveCallbacks(IWhackAMoleActions)" />
    public interface IWhackAMoleActions
    {
        /// <summary>
        /// Method invoked when associated input action "Select1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Select2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Select3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Select4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect4(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Baseball" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BaseballActions.AddCallbacks(IBaseballActions)" />
    /// <seealso cref="BaseballActions.RemoveCallbacks(IBaseballActions)" />
    public interface IBaseballActions
    {
        /// <summary>
        /// Method invoked when associated input action "Hit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHit(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ColorBlock" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ColorBlockActions.AddCallbacks(IColorBlockActions)" />
    /// <seealso cref="ColorBlockActions.RemoveCallbacks(IColorBlockActions)" />
    public interface IColorBlockActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
    }
}
