//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/InputActions/WhackAMoleInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions/WhackAMoleInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @WhackAMoleInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @WhackAMoleInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""WhackAMoleInputActions"",
    ""maps"": [
        {
            ""name"": ""WhackAMole"",
            ""id"": ""2959179e-4767-443d-9c01-363bfa296c7a"",
            ""actions"": [
                {
                    ""name"": ""SelectW"",
                    ""type"": ""Button"",
                    ""id"": ""49c42b32-8d38-4008-a92b-0c95f587f781"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectA"",
                    ""type"": ""Button"",
                    ""id"": ""0c1cc8b4-491e-4a1d-b225-2f1a93c79606"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectS"",
                    ""type"": ""Button"",
                    ""id"": ""8a054ede-20d5-4e05-999e-ba237c346bfe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectD"",
                    ""type"": ""Button"",
                    ""id"": ""a480e23f-0e2b-4f74-94ce-a17ac49a3a6b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1b9cfff9-8bad-4594-9f79-7cc91293fe18"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b37bb81-903a-4fe2-bcec-b60019666d45"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f1efb8-9d7e-482f-9469-3ff4f08a0b3a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aff4f88-8284-4d77-aa10-3488c0dfbda2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // WhackAMole
        m_WhackAMole = asset.FindActionMap("WhackAMole", throwIfNotFound: true);
        m_WhackAMole_SelectW = m_WhackAMole.FindAction("SelectW", throwIfNotFound: true);
        m_WhackAMole_SelectA = m_WhackAMole.FindAction("SelectA", throwIfNotFound: true);
        m_WhackAMole_SelectS = m_WhackAMole.FindAction("SelectS", throwIfNotFound: true);
        m_WhackAMole_SelectD = m_WhackAMole.FindAction("SelectD", throwIfNotFound: true);
    }

    ~@WhackAMoleInputActions()
    {
        UnityEngine.Debug.Assert(!m_WhackAMole.enabled, "This will cause a leak and performance issues, WhackAMoleInputActions.WhackAMole.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // WhackAMole
    private readonly InputActionMap m_WhackAMole;
    private List<IWhackAMoleActions> m_WhackAMoleActionsCallbackInterfaces = new List<IWhackAMoleActions>();
    private readonly InputAction m_WhackAMole_SelectW;
    private readonly InputAction m_WhackAMole_SelectA;
    private readonly InputAction m_WhackAMole_SelectS;
    private readonly InputAction m_WhackAMole_SelectD;
    /// <summary>
    /// Provides access to input actions defined in input action map "WhackAMole".
    /// </summary>
    public struct WhackAMoleActions
    {
        private @WhackAMoleInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public WhackAMoleActions(@WhackAMoleInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/SelectW".
        /// </summary>
        public InputAction @SelectW => m_Wrapper.m_WhackAMole_SelectW;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/SelectA".
        /// </summary>
        public InputAction @SelectA => m_Wrapper.m_WhackAMole_SelectA;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/SelectS".
        /// </summary>
        public InputAction @SelectS => m_Wrapper.m_WhackAMole_SelectS;
        /// <summary>
        /// Provides access to the underlying input action "WhackAMole/SelectD".
        /// </summary>
        public InputAction @SelectD => m_Wrapper.m_WhackAMole_SelectD;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_WhackAMole; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="WhackAMoleActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(WhackAMoleActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions" />
        public void AddCallbacks(IWhackAMoleActions instance)
        {
            if (instance == null || m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Add(instance);
            @SelectW.started += instance.OnSelectW;
            @SelectW.performed += instance.OnSelectW;
            @SelectW.canceled += instance.OnSelectW;
            @SelectA.started += instance.OnSelectA;
            @SelectA.performed += instance.OnSelectA;
            @SelectA.canceled += instance.OnSelectA;
            @SelectS.started += instance.OnSelectS;
            @SelectS.performed += instance.OnSelectS;
            @SelectS.canceled += instance.OnSelectS;
            @SelectD.started += instance.OnSelectD;
            @SelectD.performed += instance.OnSelectD;
            @SelectD.canceled += instance.OnSelectD;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions" />
        private void UnregisterCallbacks(IWhackAMoleActions instance)
        {
            @SelectW.started -= instance.OnSelectW;
            @SelectW.performed -= instance.OnSelectW;
            @SelectW.canceled -= instance.OnSelectW;
            @SelectA.started -= instance.OnSelectA;
            @SelectA.performed -= instance.OnSelectA;
            @SelectA.canceled -= instance.OnSelectA;
            @SelectS.started -= instance.OnSelectS;
            @SelectS.performed -= instance.OnSelectS;
            @SelectS.canceled -= instance.OnSelectS;
            @SelectD.started -= instance.OnSelectD;
            @SelectD.performed -= instance.OnSelectD;
            @SelectD.canceled -= instance.OnSelectD;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />.
        /// </summary>
        /// <seealso cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />
        public void RemoveCallbacks(IWhackAMoleActions instance)
        {
            if (m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="WhackAMoleActions.AddCallbacks(IWhackAMoleActions)" />
        /// <seealso cref="WhackAMoleActions.RemoveCallbacks(IWhackAMoleActions)" />
        /// <seealso cref="WhackAMoleActions.UnregisterCallbacks(IWhackAMoleActions)" />
        public void SetCallbacks(IWhackAMoleActions instance)
        {
            foreach (var item in m_Wrapper.m_WhackAMoleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WhackAMoleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="WhackAMoleActions" /> instance referencing this action map.
    /// </summary>
    public WhackAMoleActions @WhackAMole => new WhackAMoleActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "WhackAMole" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="WhackAMoleActions.AddCallbacks(IWhackAMoleActions)" />
    /// <seealso cref="WhackAMoleActions.RemoveCallbacks(IWhackAMoleActions)" />
    public interface IWhackAMoleActions
    {
        /// <summary>
        /// Method invoked when associated input action "SelectW" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectW(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectA" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectA(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectS" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectS(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectD" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectD(InputAction.CallbackContext context);
    }
}
